version: "3.2"
services:
    database:
        image: postgres:11.5
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            - PGDATA=/var/lib/postgresql/data
            - POSTGRES_PASSWORD=Bonsai-Dried-Reenact-Regulate-Prior-Tribesman-Magnifier
            - POSTGRES_USER=ptm
            - POSTGRES_DB=jail_population_warehouse
        ports:
            - "5432:5432/tcp"
        networks:
            - sparknet
    
    sparkmaster:
        image: spark_master:2.0.0
        volumes:
            - fakearchive:/bigdata
        ports:
            - "8080:8080/tcp"
            - "7077:7077/tcp"
        depends_on:
            - database
        networks:
            - sparknet

    sparkworker1:
        image: spark_worker:2.0.0
        volumes:
            - fakearchive:/bigdata
        ports:
            - "8081:8081/tcp"
        depends_on:
            - sparkmaster
        networks:
            - sparknet
    
    sparkworker2:
        image: spark_worker:2.0.0
        volumes:
            - fakearchive:/bigdata
        ports:
            - "8082:8081/tcp"
        depends_on:
            - sparkmaster
        networks:
            - sparknet

    airflowspark:
        image: airflow_spark_conda:1.0.0
        volumes:
            - fakearchive:/bigdata
        environment:
            - AIRFLOW_HOME=/home/airflow
            - POSTGRES_HOST=database
            - POSTGRES_PORT=5432
            - POSTGRES_DB=airflow
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - AIRFLOW__CORE__FERNET_KEY=uQ5Fz122Qu2yQH5PfdMrAjH0WIkgtx1df435T7GTGm4=
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
        ports:
            - "8079:8080/tcp"
        depends_on:
            - database
            - sparkmaster
            - sparkworker1
            - sparkworker2
        networks:
            - sparknet

networks:
    sparknet:

volumes:
    pgdata:
    fakearchive: